language: python
matrix:
  include:
    - name: python 3.7
      python: 3.7
      if: branch = dev
      dist: xenial
    - name: python 3.8
      python: 3.8
      if: branch = dev
      dist: xenial
    - name: python 3.9
      python: 3.9
      dist: xenial
install:
- pip install --upgrade .[qiskit,projectq,dev] coveralls
env:
- API_URL=https://staging.quantum-inspire.com
script:
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- echo "running unit tests"
- coverage run --source="./src/quantuminspire" -m unittest discover -s src/tests -t src -v
- echo "running mypy"
- MYPYPATH=./src mypy --strict --ignore-missing-imports -p quantuminspire
- echo "running pylint"
- pylint quantuminspire || true
- if [ $TRAVIS_PULL_REQUEST == "false" ] || [ $TRAVIS_BRANCH == "dev" ]; then
    echo "running examples";
    python ./docs/examples/example_projectq_entangle.py;
    python ./docs/examples/example_projectq_grover.py;
    python ./docs/examples/example_qiskit_conditional.py;
    python ./docs/examples/example_qiskit_entangle.py;
    echo "running notebooks";
    jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/examples/example_projectq.ipynb;
    jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/examples/grover_algorithm_qi.ipynb;
    jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/examples/qi-performance-test.ipynb;
  fi
after_success:
- coveralls
deploy:
  provider: pypi
  user: qinspire
  password:
    secure: Hhiv2J3i5bU25M1QlSknneMN9ZQ0KLOf1hSrS9FkmXNQFS5EIWKbSBJYP/5DeWLsezR7SxFNql1aPF3G2QLSfztELqd3avbS5qNC5ZmooDGD/PdR5XEjnUlYrn5YtBgNq+IR+91uWaBI5TZfD9bQl7lYW5LVxH2GpI9MZrx27gytxwjfqfNOTcnn/fKDn0artCQ3V+Bnu5clEGlQagNWajuYKqSCMY2gk3r5xqHPgyt7OMWk7L2ZDLiEsN8NDx3leRPWPhwVX1CCO5CR5PHSCAdc0C7Uxy8l44DgCpx8+jeLnADh7RXsHGQfj7pBX3CtbjwERBrysNtKUB4zTzkgzBpBXoI1ffCLUOmPaMdYhXveNeAWnem6aZ2lLl9+MVikPS8laPttWcRAqzDjbdFBB6D6WHvsXAFUpEllsD3AILYpD7nOEsx9uvwKlCfcgf6fmq0z5Q6Y0Kux3/oDs4AQpAPVXmWsfnbrQkaJ0Knlho+ncgrLFymvIGmMxOee8tuj6bTeOtazvCjfoDcwjT86n6qkSUZ8g/dPKMkJox8SILFpVQzOWlIwrJMzs7X65vP25nBcHYZwI7db/e+fwOwxECHvKTHf4Bubgc7FNAK7kGcobCSeC2djA83Or3LAVen58m6YCBG+AJfRHUIEkqtN2KDIuDBZfn3r8OvT3Hd2IQA=
  on:
    tags: true
    branch: master
  skip_existing: true
